server:
  servlet:
    context-path: /catalog
  port: ${PORT:8080}

spring:
  application:
    name: catalogServiceWorkshop
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: catalog
    url: jdbc:mysql://34.175.164.238:3307/CatalogDB
    username: catalog
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true